### ISSUE TITLE
Feeds are not removed

### ISSUE THREAD

**Issue by stickman33** [aigoncharov/telegram-to-rss#3]
So basicly feeds are not removed from db nor from disk. FEED_SIZE option takes not effect at all. I achived some success to remove them from db, maybe will add to next pull request. But its still a problem that they are not removing from disk. Ive already tried to change data folder in compose file to default seems no effect. Its not about r/w rights.

**Comment by fxlrnrpt** [comment]
Hmm, a bit busy in the coming days but will try to take a look over the weekend or next week. Thanks for the report!

**Comment by stickman33** [comment]
I think I got it! #4  🙂 But Ive also noticed that number of inital fetched feeds are not the same as in INITIAL_FEED_SIZE. There are lower amount in some sources. Need to dig in a little bit. Will create another issue and if have some time research it!

**Comment by fxlrnrpt** [comment]
Fantastic work! Merged and released https://github.com/aigoncharov/telegram-to-rss/releases/tag/v0.4.1
